apiVersion: v1
kind: Service
metadata:
  name: tool-warehouse
  labels:
    name: tool-warehouse
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: tool-warehouse
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tool-warehouse
spec:
  selector:
    matchLabels:
      app: tool-warehouse
  replicas: 2
  template:
    metadata:
      labels:
        app: tool-warehouse
    spec:
      containers:
        - name: tool-warehouse
          image: asierzan/tool-warehouse:0.0.5
          ports:
            - containerPort: 9000
          env:   
            - name: DB_HOST   
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: host
            - name: DB_NAME  
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER  
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials 
                  key: postgres_user
            - name: POSTGRES_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
